### ISSUE TITLE
Atlanta RailsBridge April 2015

### ISSUE THREAD

**Issue by KyFaSt** [railsbridge/organizing#52]
This workshop's going to be amazing!! Here's what we need to do! We'd like to schedule this event in conjunction with RailsConf coming to Atlanta April 21st-23rd

General:
- [x] make a [sweet wrap up flyer](https://dl.dropboxusercontent.com/u/55826860/RailsBridge/more-resources-flyer.pdf) so atteendees will have resources to keep learning after the workshop

A few months out:
- [x] Find a venue-this might be difficult with a Monday workshop (20th)
  - We'll be using [Polygon ATL](http://polygonatl.com/)
- [x] Find a sponsor for the workshop. This workshop covers RailsBridge 'vanilla'.  Sponsoring the workshop will cost about $1600 since we are using a paid space
- [x] Find two co-organizers. It's a lot of work, but always a lot of fun. No experience is necessary; checkout the [workshop cookbook](https://github.com/railsbridge/docs/wiki/Cookbook) if it's new to you. (Also, we match up first time organizers with mentors.)
  - [x] @kyfast
  - [x] @pwnela
  - [x] @lclindeman
  - [x] @beverlynelson has graciously offered to serve as an organizing mentor

Leave a comment below if you're able to host, sponsor or organize! :smile_cat: 

Once we have a a venue, sponsors, and organizers, we can:
- [x] Work together to set an RSVP limit that works for everyone
- [x] Post the workshop to [Bridge Troll](http://www.bridgetroll.org/)

One to two weeks out, we can:
- [x] Plan a teacher training
- [ ] Order installfest food
- [ ] Order breakfast
- [ ] Order lunch
- [ ] Find a good place for the afterparty

After the workshop, we can:
- [ ] Party! :tada:   
- [ ] Retro

:tulip:

**Comment by lilliealbert** [comment]
Hi @KyFaSt, @pwnela, & @lclindeman — I'm taking a look at your Bridge Troll posting, and the title seems a little bit odd to me, since RailsBridge and Rails Girls are quite separate things. I'm just a little worried that people will be confused. Does that seem silly?

**Comment by lclindeman** [comment]
Hey Lillie!

Thanks for reaching out. I can see how it might be confusing. The reason we titled it that way is because we have quite an active Rails Girls group here in Atlanta that meets monthly and has over 300 members on Meetup. We’ve held occasional one-day Rails Girls workshops, but, in general, we’ve long since stopped following the actual Rails Girls curriculum in favor of holding talks and working through other tutorials together. All of us are involved in that group, and it’s that group’s support that is making it possible for us to put on a Rails Bridge workshop. So, we wanted to leverage the recognition our Rails Girls group has to make this workshop a success.

Does that make more sense? Let us know if we still need to tweak it.

Best,
Laura

**Comment by pwnela** [comment]
Hi @lilliealbert! We know this isn't conventional, but we held two Rails Girls workshops here in Atlanta in previous years which has turned into a successful monthly meetup a couple years running. Since Rails Girls Atlanta is an established and recognized community in Atlanta, we thought it made sense to state who was organizing the Railsbridge workshop. (It would be like any other developer group putting together an event... we just happen to have a name associated with a different workshop!)

**Comment by pwnela** [comment]
Oops, I guess @lclindeman was replying at the same time!

**Comment by mfjenn** [comment]
As a non-Atlantian who has been to a Rails Girls event in Atlanta, I can
back that up. Rails girls is more active there than Railsbridge and I'm
glad to see you leveraging the branding to bring railsbridge to Atlanta!

Good luck with the partnership and the event!

**Comment by pwnela** [comment]
@mfjenn was a huge help as a coach at one of our Rails Girls workshops! (Hi!!)

**Comment by lilliealbert** [comment]
Okay, it sounds like it will make sense to folks in Atlanta, which is what counts. :dancers: 

One other details with the Bridge Troll listing is that it doesn't explicitly state who the event is reaching out to — could you add whether students need to be women to attend? 

(RailsBridge workshops often allow people outside the target demographic to attend if they're the guest of the target demographic, so we try to make sure that we're being explicit about who is invited to attend / volunteer.)

**Comment by mfjenn** [comment]
I’m just going to add: ...since our mission is about diversifying the dev community.

**Comment by mfjenn** [comment]
Hi Pamela! It was fun and a good group!

**Comment by lclindeman** [comment]
I added a sentence about who should attend! Please let me know if that covers it...I'm happy to make edits if it needs to be even more clear!

**Comment by sarahmei** [comment]
Super excited about this. Do you want Ruby Central to help publicize? We can tweet from @railsconf etc. if useful.

**Comment by beverlynelson** [comment]
@pwnela I know I offered to be an organizing mentor by email but if you have space for an extra volunteer on site we might end up making the trip to ATL after all.  Still pending but wanted to see what your needs were on that front.

**Comment by pwnela** [comment]
@sarahmei that would be great!! I think @lclindeman was planning for us to announce it this coming Friday.

And @beverlynelson of course! That would be so helpful. Hope you can make it up!

**Comment by lclindeman** [comment]
@sarahmei We would love for you to help publicize! Our listing is not live yet on Bridge Troll (just waiting for it to be okayed), so we don't have anywhere to point yet, but as soon as it is I'll ping you!

**Comment by lilliealbert** [comment]
Published on Bridge Troll! 

One other thing I noticed is this language:

>  Please note: this session is required if you do no have Ruby, Rails, Git & Heroku set up. Already have everything installed? No problem! Come by anyway to help out and to meet your fellow workshop-ees.

We have pretty consistent problems where people have attending a workshop in the past, or have set up all the various component a month or two ago, and then when they arrive at the workshop in the AM and things are all busted, and they have to debug with a TA instead of being present in the workshop. I'd recommend saying that the Installfest is mandatory for everyone.

**Comment by lclindeman** [comment]
No problem, that makes sense and I'll tweak it!

**Comment by KyFaSt** [comment]
Right, that makes sense to have everyone attend the installfest to confirm that everything is set up properly. Thanks for pointing this out @lilliealbert :smile:

**Comment by lilliealbert** [comment]
:tada: :tada: :tada:

**Comment by pdougall1** [comment]
RailsBridge April 2015 WOOP!

**Comment by KyFaSt** [comment]
@lilliealbert should we close this issue now?

**Comment by lilliealbert** [comment]
:tada: :tada: :tada: yeah!!! :tada: :tada: :tada:
