### ISSUE TITLE
Triangle Feb 20&21 Rails Workshop at HQ Raleigh

### ISSUE THREAD

**Issue by maebeale** [railsbridge/organizing#57]
Hey there! We're planning a Feb 20&21 Rails Workshop (for underrepresented groups in tech) at HQ Raleigh from our new chapter, RailsBridge Triangle (Raleigh/Durham/Chapel Hill). We've submitted a bridge troll but haven't heard back in a few days. Might anyone be able to contact me about next steps? Many thanks and best from North Carolina!

**Comment by ruchikakumar** [comment]
Hi @maebeale  cc'ing @aneyzberg  and @ celestelayne form SF team.  We can help.

**Comment by ruchikakumar** [comment]
@celestelayne

**Comment by aneyzberg** [comment]
I believe @lilliealbert is the one that approves the Bridgetroll posts correct? @lilliealbert can you answer this question?

**Comment by lilliealbert** [comment]
Yes, @maebeale, I sent you an email — well, I sent an email to the email address listed on the event, RailsBridgeTriangle@gmail.com —about specifying which underrepresented group the workshop was for, and hadn't heard back yet.

Basically, the RailsBridge Triangle website says that the workshops are for women, and the Bridge Troll posting says "This workshop is intended to reach out to underrepresented groups in tech who are interested in learning Ruby on Rails. Registered students are welcome to bring one guest." I wondered if it wouldn't make sense to have those be in agreement before posting the workshop.

**Comment by maebeale** [comment]
hello there! thanks so much, and i apologize to not have responded from the other email (we are a core team of 6, and i'm not maintaining that gmail account). thanks for noticing that! there's a PR that hasn't been published yet  (https://github.com/railsbridgetriangle/railsbridgetriangle.github.io/commit/5edf0d0883ce64fd6a952fb29ccfc1755be0e0d1) on our site's repo to change the text, so that's why there's a discrepancy. the revised text should get published today. and yes, we definitely want them in sync, so thanks!

**Comment by maebeale** [comment]
hello there! we're live. http://railsbridgetriangle.com/. i'd figured we could sync amongst ourselves, but great to know you're checking on these details, so tks for being awesome!

**Comment by maebeale** [comment]
hey there! thanks for getting our event posted!!! i'm looking for a way to edit some default text in our BridgeTroll event listing (remove the line w the link to the curriculum). is this something we can request and/or submit a PR for? many thanks! mae

**Comment by lilliealbert** [comment]
What curriculum are you planning on using? If there was a new curriculum that you were writing that we could add to http://docs.railsbridge.org/, it would be totally awesome to merge it into the rest of the docs rather than have a whole separate curriculum for just your chapter.

Right now, all the RailsBridge curricula types are listed as options, and we don't have a way to list a different curriculum. We can look into whether it'd be better not to link to the curriculum in the description by default, or change the way we deal with it, but I'd love to figure out where your curriculum lives / the reasoning behind having it separate before we talk about feature changes to Bridge Troll. 

(cc: @tjgrathwell, who is the main contributor to Bridge Troll)

**Comment by maebeale** [comment]
Lillie (and Travis), hello! 

Excellent questions -- all of them. 

Your site led us to believe it was welcomed to adapt the main curriculum as we saw fit, so we've been working through slight tweaks, and apologize for any confusion on our end. And yes, it'd be awesome if y'all wanted to accept changes from us to the curriculum so our chapter isn't an outlier. And/or to contemplate adding an option for us to opt in or out of the default curriculum.

@mxhold is our team's lead on curriculum, so I'm going to involve him in this discussion to best answer where we're contemplating slight deviations.

Thanks for discussing this with us!

**Comment by lilliealbert** [comment]
@maebeale, yeah, there's definitely been a culture of "do what you want" with RailsBridge historically, so it's not surprising that you got that impression, and since everything is open source, we aren't going to stop anyone from forking and making changes :smiley: 

But! RailsBridge leadership is also grappling with how we can keep the curricula as fresh and awesome as possible, and one of the biggest ways to do that is to have new folks (like yourselves) making pull requests and changes to the curriculum. When chapters fork the repo and makes their own thing, all the chapters that use the main curriculum get fewer updates. (We're also working on / thinking about how to make update the docs feel more accessible to new volunteers / chapters — I can totally see the appeal of forking so that you can make your own changes and not wait for acceptance + deployment.)

I would love feedback on where/how RailsBridge could better indicate that forking is welcome, but that pull requests with updates are vastly preferred so that we can share in the wealth of collaboration. :cake:

**Comment by mxhold** [comment]
Thanks for including me in this @maebeale.

My plan was to fork the curriculum and make pull requests for all my changes so we wouldn't have to use the forked one in the end. I haven't been on top of that lately... my bad. I have a list of some basic changes already and there are some more I'd like to do. I think I'll get around to making those into actually pull requests later this week.

I think our initial desire for linking to the forked curriculum from the start was just that if we departed too much from the normal curriculum we wouldn't have to worry about merging all of the changes before the event. But I agree that contributing to one set of curricula will help future chapters the most so I will try to put my changes in the form of pull requests.

@lilliealbert Thanks for emphasizing that pull requests are preferred. :+1: I think my biggest reluctance with jumping into them right off the bat was just not knowing exactly what kinds of changes were welcome and which were not (small spelling changes vs adding entirely new steps vs removing others, etc.). A lot of these decisions about how to best present things are subjective and that can make it difficult to arrive at the same place but I feel more comfortable making suggestions after reading your remarks. :smile:

**Comment by lilliealbert** [comment]
@mxhold Cool, all of that makes sense. I personally like more, smaller pull requests, so that if one part generates a lot of discussion, it doesn't block the acceptance of other bits.

And yeah, I totally feel you on not knowing what kinds of changes are okay, since don't really say anywhere! That could use some explicit stating in the readme. We're generally pretty friendly, so even if you make a pull request with a terrible change (replacing all the instances of the word Rails with Butts, perhaps), we won't be mean :smile:

(Maybe you already know all this stuff, but I found GitHub's [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request) to be really helpful, especially for one's first PR on a repo.)

**Comment by lilliealbert** [comment]
This totally happened! Woo! https://www.bridgetroll.org/events/138

**Comment by maebeale** [comment]
:)

Thanks, much! And next weekend is our next event! :)

Best to you and the rest at RailsBridge!
mae
